version: '3'

services:

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    volumes:
      - .:/code:cached
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

volumes:
  postgres-data: