version: '3'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    volumes:
      - name_app:/name_app:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - db
volumes:
  postgres-data:
  name_app: