version: '3'

services:

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password

  python:
    image: python:3.8
    volumes:
      - ../:/Mastering_DS_ML
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - db
volumes:
  postgres-data:
  